version: "3"
services:
    app: 
        container_name: docker-api
        restart: always
        build: .
        ports: 
            - '3001:3001'
        links:
            - db
    db:
        container_name: docker-db
        image: mongo
        ports: 
            - '27017:27017'
        volumes:
            - 'C:\Users\robbie.redfearn\Desktop\d_coding-test\server\database:/data/db'